### ISSUE TITLE
Post - body field as modular child sections

### ISSUE THREAD

**Issue by michaelburtonray** [human-nyc/spree-blogging-spree#11]
I think we need to create a child model called Section for the body of a post. you can add/subtract sections in a post so it is a has_many relationship. A select dropdown will let you choose different layouts (using enum):

- [x] text
- [x] text and image
- [x] image and text
- [x] pull quote (this potentially could just be the text layout + then using blockquote in the wysiwyg editor)
- [x] Image gallery
- [x] Collection of products

This is kind of an open ended ticket, lets work on what we know should be there and then get to the unknowns when it comes to that.

**Comment by RachaelYaeger** [comment]
Hey @aaronzdavis! Do you want these broken out in separate tickets? @michaelburtonray is going to start styling the front-end so I want to know where we are at the back-end when you get a moment :+1:
