### ISSUE TITLE
Remove/hide Author field—add Byline textarea field

### ISSUE THREAD

**Issue by michaelburtonray** [human-nyc/spree-blogging-spree#2]
Remove Author field (or just hide it)
![screen shot 2016-03-14 at 11 24 07 am](https://cloud.githubusercontent.com/assets/188906/13749352/549f05b8-e9d7-11e5-9396-9f9c27226c0a.png)

Byline field should be a plain textarea field to hold multiline plain text like 
```
Words by Alessandro Simonetti
Photographs by Renato D’Agostin
```
![screen shot 2016-03-14 at 11 23 54 am](https://cloud.githubusercontent.com/assets/188906/13749353/54a0b41c-e9d7-11e5-9766-63628b405b12.png)

**Comment by aaronzdavis** [comment]
@michaelburtonray You don't think they'll want the Author / Photographers name linkable?

**Comment by michaelburtonray** [comment]
@aaronzdavis Lemme find out

**Comment by michaelburtonray** [comment]
@aaronzdavis Nope, client says that will just be plain text.
