### ISSUE TITLE
Rails assumes aws-sdk is used for Image uploads.

### ISSUE THREAD

**Issue by michaelburtonray** [human-nyc/spree-blogging-spree#7]
Find a way to set the uploading to utilize the filesystem so we don't have to sign up for Amazon Web Services.

**Comment by michaelburtonray** [comment]
![screen shot 2016-03-16 at 6 06 32 pm](https://cloud.githubusercontent.com/assets/188906/13830668/8a43d7a6-eba4-11e5-8b72-ad341f8a78ff.png)

**Comment by aaronzdavis** [comment]
@michaelburtonray Will have to test file writing permissions on the server
